### ISSUE TITLE
DoctorsView

### ISSUE THREAD

**Issue by Elajjten** [lagerqvisst/OOSU2-VT24-LAB2-Grupp-1#60]
Det ser lite troll ut när programmet körs, kolla bifogad bild
![oosu2 docapp](https://github.com/lagerqvisst/OOSU2-VT24-LAB2-Grupp-1/assets/153810803/3b17c45c-33dd-4a18-b731-442044a0d350)

(detta e lite av ett test för att se om de går att bifoga bilder

**Comment by lagerqvisst** [comment]
Verkar löst när jag la till en scrollbar på varje datagrid. 
Den på vänstersida tycks vara där för att kunna markera allt (?), osäker. 
Men den på högersida verkar borta. 

![image](https://github.com/lagerqvisst/OOSU2-VT24-LAB2-Grupp-1/assets/108764890/7f6f157a-e521-43d7-ab5b-b19ff948b56e)


![image](https://github.com/lagerqvisst/OOSU2-VT24-LAB2-Grupp-1/assets/108764890/e727160b-2aa8-4316-9f06-4fdedb37f9b9)

**Comment by Elajjten** [comment]
Snyggt

**Comment by lagerqvisst** [comment]
Stänger denna då.
